# Generated by Django 2.2.18 on 2021-02-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_group"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="author",
        ),
        migrations.RemoveField(
            model_name="course",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.RemoveField(
            model_name="module",
            name="course",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="event",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
